[package]
name = "loreloom-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
loreloom-core = { version = "0.1.0", path = "../loreloom-core" }

[dev-dependencies]
crossterm = "0.29.0"
ratatui = { version = "0.30.2", default-features = false, features = ["crossterm"] }
unicode-segmentation = "1.13.3"
